name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *" # Run daily
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Sync Upstream to develop
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Clone the fork
        git clone https://github.com/Rolln-dev/MOOSE_INCLUDE-ROLLN-FORK.git work
        cd work

        # Set up Git config
        git config user.name "Rolln-dev"
        git config user.email "RollnThndr@gmail.com"

        # Add the upstream repository
        git remote add upstream https://github.com/FlightControl-Master/MOOSE_INCLUDE.git
        git fetch upstream

        # Check out the remote branch to a local branch
        git checkout -B develop origin/develop

        # Merge changes from upstream into the local branch
        git merge upstream/develop

        # Push changes back to the fork
        git push origin develop
